import type { Locator, Page } from '@playwright/test';
import { expect, test } from '../lib/harness.ts';

test('タグタブで付与と解除が保存され、投稿を切り替えてもタブを維持する', async ({ launchHologram }) => {
  const { page } = await launchHologram();
  const cards = page.locator('[data-slot="post-grid"] [data-slot="post-card"]');
  const card = cards.filter({ hasText: '猫が机の上で寝ている' });
  await card.click();
  const inspector = page.locator('[data-slot="inspector"]');
  await inspector.getByRole('tab', { name: 'タグ', exact: true }).click();
  const input = inspector.locator('[data-slot="tag-input"]');
  await input.fill('タグタブ確認');
  await input.press('Enter');
  await expect(inspector.locator('[data-slot="tag-chip"][data-tag="タグタブ確認"]')).toBeVisible();
  await cards.filter({ hasNotText: '猫が机の上で寝ている' }).first().click();
  await expect(inspector.getByRole('tab', { name: 'タグ', exact: true })).toHaveAttribute('aria-selected', 'true');
  await card.click();
  await input.fill('タグタブ確認');
  const checkbox = inspector.getByRole('checkbox', { name: 'タグタブ確認', exact: true });
  await expect(checkbox).toBeChecked();
  await checkbox.click();
  await expect(checkbox).toHaveCount(0);
  await expect(inspector.locator('[data-slot="tag-chip"][data-tag="タグタブ確認"]')).toHaveCount(0);
  await inspector.getByRole('tab', { name: '詳細', exact: true }).click();
  await expect(inspector.locator('[data-slot="inspector-post"]')).toBeVisible();
});

test('グループ作成、タグ作成、折りたたんだ移動先へのドラッグと右クリック編集', async ({ launchHologram }) => {
  const { page } = await launchHologram();
  await page.locator('[data-slot="post-grid"] [data-slot="post-card"]').first().click();
  const inspector = page.locator('[data-slot="inspector"]');
  await inspector.getByRole('tab', { name: 'タグ', exact: true }).click();
  await inspector.getByRole('button', { name: 'グループを作成', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox').fill('移動先');
  await dialog.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(inspector.locator('summary').filter({ hasText: '移動先' })).toBeVisible();
  await inspector.getByRole('button', { name: 'タグを作成', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox', { name: 'タグ名', exact: true }).fill('ドラッグ確認');
  await dialog.getByRole('button', { name: '作成して追加', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const destination = inspector.locator('details').filter({ has: page.locator('summary', { hasText: '移動先' }) });
  await destination.locator('summary').click();
  const row = inspector.locator('label').filter({ hasText: 'ドラッグ確認' });
  await expect(row).toHaveAttribute('data-tag-draggable', 'true');
  await dragTag(page, row, destination.locator('summary'));
  await destination.locator('summary').click();
  await expect(destination.getByRole('checkbox', { name: 'ドラッグ確認', exact: true })).toBeChecked();
  await destination.locator('summary').click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'グループ名を変更', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox').fill('変更先');
  await dialog.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(inspector.locator('summary').filter({ hasText: '変更先' })).toBeVisible();
  await inspector.locator('label').filter({ hasText: 'ドラッグ確認' }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'グループを変更', exact: true }).click();
  await expect(page.getByRole('menuitem', { name: 'グループを作成', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(inspector.getByRole('button', { name: 'タグを管理…', exact: true })).toHaveCount(0);
  await inspector.locator('label').filter({ hasText: 'ドラッグ確認' }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'タグ名を変更', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox').fill('名前変更済み');
  await dialog.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(inspector.getByRole('checkbox', { name: '名前変更済み', exact: true })).toBeChecked();
  await inspector.locator('label').filter({ hasText: '名前変更済み' }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'タグ名を変更', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox').fill('ラフ');
  await dialog.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page.getByRole('alertdialog')).toContainText('同じ名前のタグがあります');
  await page.getByRole('alertdialog').getByRole('button', { name: '統合する', exact: true }).click();
  await expect(inspector.getByRole('checkbox', { name: '名前変更済み', exact: true })).toHaveCount(0);
  await expect(inspector.getByRole('checkbox', { name: 'ラフ', exact: true })).toBeChecked();
  await inspector.locator('label').filter({ hasText: 'ラフ' }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: '削除', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: '削除', exact: true }).click();
  await expect(inspector.getByRole('checkbox', { name: '名前変更済み', exact: true })).toHaveCount(0);
  await expect(inspector.getByRole('checkbox', { name: 'ラフ', exact: true })).toHaveCount(0);
  await expect(page.locator('[data-slot="post-grid"] [data-slot="post-card"]').first()).toBeVisible();
});

async function dragTag(page: Page, source: Locator, destination: Locator) {
  await source.scrollIntoViewIfNeeded();
  const from = await source.boundingBox();
  const to = await destination.boundingBox();
  if (!from || !to) throw new Error('ドラッグ対象が表示されていません');
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
  await page.mouse.down();
  await page.waitForTimeout(300);
  await page.mouse.move(from.x + from.width / 2 + 8, from.y + from.height / 2, { steps: 3 });
  await expect(page.locator('[data-slot="tag-drag-preview"]')).toBeVisible();
  await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 12 });
  await expect(destination.locator('xpath=ancestor-or-self::*[@data-drop-target="true"]')).toBeVisible();
  await page.mouse.up();
}
