import { expect, test } from '../lib/harness.ts';

test('閲覧と編集を切り替え、保存とキャンセルを区別する', async ({ launchHologram }) => {
  const hologram = await launchHologram();
  const { page } = hologram;
  await page.locator('[data-slot="post-card"]').filter({ hasText: '猫が机の上で寝ている' }).dblclick();
  const toolbar = page.locator('[data-slot="viewer-toolbar"]');
  await expect(toolbar).toBeVisible();
  await expect(page.locator('[data-slot="image-tab-info"]')).toHaveCount(0);
  await expect(page.locator('[data-slot="inspector-toggle"]')).toBeVisible();
  await expect(toolbar.locator('button')).toHaveCount(4);
  const edits = () => hologram.readDb((db) => db.prepare('SELECT rotation,flipped,cropX FROM media ORDER BY postId,seq').all());
  const before = edits();
  const detail = await page.locator('[data-slot="inspector-toggle"]').boundingBox();
  const tools = await toolbar.boundingBox();
  if (!tools || !detail) throw new Error('ツールバーが表示されていません');
  expect(tools.x + tools.width).toBeLessThan(detail.x);
  await expect(page.locator('[data-slot="image-tab-stage"] [data-slot="image-tab-crop"]')).toHaveCount(0);
  await toolbar.locator('[data-slot="viewer-edit"]').click();
  await expect(page.locator('[data-slot="image-editor"]')).toBeVisible();
  await toolbar.locator('[data-slot="viewer-rotate"]').click();
  await expect(toolbar.locator('[data-slot="viewer-flip"]')).toBeEnabled();
  await toolbar.locator('[data-slot="viewer-flip"]').click();
  await toolbar.locator('[data-slot="image-tab-crop"]').click();
  await expect(page.locator('[data-slot="crop-selection"]')).toBeAttached();
  await page.getByRole('button', { name: 'キャンセル', exact: true }).click();
  await expect(page.locator('[data-slot="crop-selection"]')).toHaveCount(0);
  expect(edits()).toEqual(before);
  await expect(toolbar.locator('[data-slot="viewer-grid"], [data-slot="viewer-grayscale"]')).toHaveCount(0);
  const fit = toolbar.locator('[data-slot="viewer-fit-toggle"]');
  await expect(fit).toHaveAccessibleName(/ウィンドウ/);
  const level = toolbar.locator('[data-slot="viewer-zoom-level"]');
  await expect(level).not.toHaveText('—');
  const initial = (await level.textContent()) ?? '';
  await toolbar.locator('[data-slot="viewer-zoom-in"]').click();
  await expect(level).not.toHaveText(initial);
  await fit.click();
  await expect(level).toHaveText(initial);
  await fit.click();
  await page.waitForTimeout(250);
  await expect(level).toHaveText(initial);
  await toolbar.locator('[data-slot="viewer-edit"]').click();
  await toolbar.locator('[data-slot="viewer-rotate"]').click();
  await toolbar.locator('[data-slot="viewer-flip"]').click();
  await toolbar.locator('[data-slot="image-tab-crop"]').click();
  const handle = page.locator('.ReactCrop__drag-handle.ord-se');
  const bounds = await handle.boundingBox();
  if (!bounds) throw new Error('クロップのハンドルがありません');
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x - 25, bounds.y - 25, { steps: 4 });
  await page.mouse.up();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.locator('[data-slot="image-editor"]')).toHaveCount(0);
  expect(edits().some((row: any) => row.rotation === 90 && row.flipped === 1)).toBe(true);
  expect(edits().some((row: any) => row.cropX != null)).toBe(true);
  await page.reload();
  await expect(toolbar.locator('[data-slot="viewer-edit"]')).toBeEnabled();
  await toolbar.locator('[data-slot="viewer-edit"]').click();
  await expect(toolbar.locator('[data-slot="viewer-flip"]')).toHaveAttribute('aria-pressed', 'true');
  await toolbar.locator('[data-slot="viewer-reset-edits"]').click();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.locator('[data-slot="image-editor"]')).toHaveCount(0);
  expect(edits()).toEqual(before);
});
