name: 機能の提案
description: 解決したい困りごとと、そのための機能を提案する。
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したいこと
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 考えている解決方法

  - type: textarea
    id: alternatives
    attributes:
      label: ほかに試した方法
