'use strict';

// Regenerate EVERY brand icon from one master image.
//
//   1. Replace the master:  assets/icon-master.png   (square, >=512px)
//   2. Run:                 app/node_modules/.bin/electron scripts/make-icons.cts
//
// That single run rewrites every derived icon listed in TARGETS below, so an icon
// swap can never go half-done (the recurring pain before this script existed). It
// runs under Electron purely for nativeImage's high-quality resampler — no window,
// no network, just file I/O into the repo. Add a new icon location? Add it to
// TARGETS (raster) or BANNERS (svg) and it joins the one-shot regen.
//
// The brand mark is the holographic iridescent square (the app icon, generated by
// the Claude Design shader in app/renderer/about-icon.ts). It is inherently raster,
// so there is no vector master — assets/icon-master.png is the source of truth.

const { app, nativeImage } = require('electron');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const MASTER = path.join(ROOT, 'assets', 'icon-master.png');

// Every raster icon the project ships, with its square size. Keep this list complete
// — it is the manifest of "where the icon lives".
const TARGETS = [
  { file: 'app/assets/icon.png', size: 512 }, // Electron window/taskbar + electron-builder source (->.ico)
  { file: 'assets/icon.png', size: 256 }, // general brand raster / favicon
  { file: 'extension/icons/icon256.png', size: 256 },
  { file: 'extension/icons/icon128.png', size: 128 },
  { file: 'extension/icons/icon48.png', size: 48 },
  { file: 'extension/icons/icon32.png', size: 32 },
  { file: 'extension/icons/icon16.png', size: 16 },
];

// README banners: the wordmark + tagline are kept verbatim; only the leading mark
// (the single <g>…</g> group) is swapped for the holographic square as an embedded
// raster. GitHub renders the banner via <img>, which blocks external refs, so the
// square must be inlined as a base64 data URI.
const BANNERS = ['banner-light.svg', 'banner-dark.svg', 'banner-en-light.svg', 'banner-en-dark.svg'];
const BANNER_ICON = { x: 10, y: 14, size: 76, render: 200 }; // placement in the 480x104 viewBox

function fail(msg) {
  console.error('make-icons: ' + msg);
  app && app.exit(1);
  process.exit(1);
}

function run() {
  if (!fs.existsSync(MASTER)) fail('missing master ' + MASTER + ' — put the square icon there first.');
  const master = nativeImage.createFromPath(MASTER);
  if (master.isEmpty()) fail('could not decode ' + MASTER);
  const { width, height } = master.getSize();
  if (width !== height) console.warn(`make-icons: master is ${width}x${height} (not square) — output may distort.`);
  if (width < 256) console.warn(`make-icons: master is only ${width}px — small targets are fine but 512+ is recommended.`);

  for (const t of TARGETS) {
    const out = master.resize({ width: t.size, height: t.size, quality: 'best' });
    const abs = path.join(ROOT, t.file);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, out.toPNG());
    console.log('wrote ' + t.file);
  }

  // Banner: one shared square data URI, dropped into each variant's SVG.
  const b64 = master.resize({ width: BANNER_ICON.render, height: BANNER_ICON.render, quality: 'best' }).toPNG().toString('base64');
  const { x, y, size } = BANNER_ICON;
  const imageTag = `<image x="${x}" y="${y}" width="${size}" height="${size}" href="data:image/png;base64,${b64}"/>`;
  for (const name of BANNERS) {
    const abs = path.join(ROOT, 'assets', name);
    if (!fs.existsSync(abs)) {
      console.warn('skip ' + name + ' (missing)');
      continue;
    }
    let svg = fs.readFileSync(abs, 'utf8');
    if (!/<g\b[\s\S]*?<\/g>/.test(svg)) {
      console.warn('skip ' + name + ' (no <g> mark to replace)');
      continue;
    }
    svg = svg.replace(/<g\b[\s\S]*?<\/g>/, imageTag);
    fs.writeFileSync(abs, svg);
    console.log('wrote assets/' + name);
  }

  console.log('done — regenerated ' + (TARGETS.length + BANNERS.length) + ' artifacts from assets/icon-master.png');
}

app.disableHardwareAcceleration();
app.whenReady().then(() => {
  try {
    run();
  } catch (e) {
    fail((e && e.message) || String(e));
  }
  app.quit();
});
